In [ ]:
print("Hello World!")
today = 'Jan 14'
print(f"Today is {today}")


Hello World!
Today is Jan 14


In [2]:
import numpy as np

# Magic Functions
Use the character % to initiate magic functions

In [4]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is F4E8-16E7

 Directory of c:\Users\caelc\Documents\Spring 2026\Data Science\notes

01/14/2026  08:30 AM    <DIR>          .
01/12/2026  09:11 AM    <DIR>          ..
01/12/2026  09:26 AM             1,983 Jan12.ipynb
01/14/2026  08:49 AM             2,110 Jan14.ipynb
               2 File(s)          4,093 bytes
               2 Dir(s)  21,782,626,304 bytes free


In [5]:
%pwd

'c:\\Users\\caelc\\Documents\\Spring 2026\\Data Science\\notes'

Other magic commands
* `%paste` and `%cpaste`
* `%matplotlib inline`

In [1]:
import seaborn as sb
sb.scatterplot?

Matplotlib is building the font cache; this may take a moment.


Signature:
sb.scatterplot(
    data=None,
    *,
    x=None,
    y=None,
    hue=None,
    size=None,
    style=None,
    palette=None,
    hue_order=None,
    hue_norm=None,
    sizes=None,
    size_order=None,
    size_norm=None,
    markers=True,
    style_order=None,
    legend='auto',
    ax=None,
    **kwargs,
)
Docstring:
Draw a scatter plot with possibility of several semantic groupings.

The relationship between `x` and `y` can be shown for different subsets
of the data using the `hue`, `size`, and `style` parameters. These
parameters control what visual semantics are used to identify the different
subsets. It is possible to show up to three dimensions independently by
using all three semantic types, but this style of plot can be hard to
interpret and is often ineffective. Using redundant semantics (i.e. both
`hue` and `style` for the same variable) can be helpful for making
graphics more accessible.

See the :ref:`tutorial <relational_tutorial>` for more information.

The def

# Lists of numbers
- Tuple
- List
- Dictionary
- Array

In [5]:
tup1 = (3,7)
print(tup1[1])

7


In [ ]:
# Tuple
tup1 = (3, 7, 9, 13, 'Hello')
print(tup1)

(3, 7, 9, 13, 'Hello')


In [9]:
# List
list1 = [3, 7, 9, 13, 'Hello']
print(list1)
list1[4] = 'World'
print(list1)
list1.append(9)
print(list1)

[3, 7, 9, 13, 'Hello']
[3, 7, 9, 13, 'World']
[3, 7, 9, 13, 'World', 9]


In [11]:
# Array
arr1 = np.array([3, 7, 9, 13, 'Hello'])
print(arr1)
# Array's have to have the same data type

['3' '7' '9' '13' 'Hello']


In [13]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Matrix Multiplication
np.matmul(arr2, arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
arr3 = np.array([13, 17, 19])
np.matmul(arr2, arr3)

array([104, 251, 398])

In [16]:
arr4 = np.array([7, 4, 1])
print(np.matmul(arr3, arr4))
print(np.dot(arr3, arr4))

178
178


In [1]:
# Dictionary
dict1 = {
    'Name' : 'Harry',
    'Class' : 'MATH 3080',
    'Grade' : 96,
    'GPA' : 4.0,
    'Degree' : 'B.S in SE'
}
print(dict1)
dict1['Name']

{'Name': 'Harry', 'Class': 'MATH 3080', 'Grade': 96, 'GPA': 4.0, 'Degree': 'B.S in SE'}


'Harry'

In [3]:
dict2 = {
    'Name' : ['Harry', 'Landon'],
    'GPA' : [4.0, 3.9]
}
print(dict2)
dict2['GPA'][1]

{'Name': ['Harry', 'Landon'], 'GPA': [4.0, 3.9]}


3.9

In [5]:
import pandas as pd
# PanDa = Panel Data

# DataFrame
df2 = pd.DataFrame(dict2)
print(df2)

     Name  GPA
0   Harry  4.0
1  Landon  3.9


In [6]:
display(df2)

,Name,GPA
0,Harry,4.0
1,Landon,3.9


In [ ]:
# pd.read_csv('./dataset/file.csv')
# You can replace the file path with a URL if it is online

In [7]:
pd.Series(dict2['GPA'], index=dict2['Name'])

Harry     4.0
Landon    3.9
dtype: float64

In [ ]:
# Only shows the first 5 rows by default
df2.head()

# You can specify how many
df2.head(20)

In [11]:
import numpy as np
obs = np.random.randint(0,100,10)
obs

array([49, 65,  1, 94,  2, 95, 76, 64,  0, 24], dtype=int32)

In [ ]:
# gets only those observations
df2.loc[obs]

In [12]:
# Gives column names
df2.columns

Index(['Name', 'GPA'], dtype='object')

In [13]:
df2['GPA']

0    4.0
1    3.9
Name: GPA, dtype: float64